# The blocks that the drill can't break
# Block list: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
disabled_blocks:
- BEDROCK
- PORTAL
- ENDER_PORTAL
- ENDER_PORTAL_FRAME
- END_CRYSTAL

# The maximum distance between the drill and the block to break
max_distance: 128

# Fuels
# Format: item/block: broken_blocks
fuels:
  SUGAR_CANE: 1


# Drill bits
# Format: block: modifier
# Formula used to calculate the amount of fuel used: modifier * broken_blocks
# Example: sugar cane with diamond block as the bit = 1 * 1 = 1 sugar cane/broken block
bits:
  IRON_BLOCK: 2
  DIAMOND_BLOCK: 1